/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface TestComponent {
    }
    interface TestComponentInner {
    }
}
declare global {
    interface HTMLTestComponentElement extends Components.TestComponent, HTMLStencilElement {
    }
    var HTMLTestComponentElement: {
        prototype: HTMLTestComponentElement;
        new (): HTMLTestComponentElement;
    };
    interface HTMLTestComponentInnerElement extends Components.TestComponentInner, HTMLStencilElement {
    }
    var HTMLTestComponentInnerElement: {
        prototype: HTMLTestComponentInnerElement;
        new (): HTMLTestComponentInnerElement;
    };
    interface HTMLElementTagNameMap {
        "test-component": HTMLTestComponentElement;
        "test-component-inner": HTMLTestComponentInnerElement;
    }
}
declare namespace LocalJSX {
    interface TestComponent {
    }
    interface TestComponentInner {
    }
    interface IntrinsicElements {
        "test-component": TestComponent;
        "test-component-inner": TestComponentInner;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "test-component": LocalJSX.TestComponent & JSXBase.HTMLAttributes<HTMLTestComponentElement>;
            "test-component-inner": LocalJSX.TestComponentInner & JSXBase.HTMLAttributes<HTMLTestComponentInnerElement>;
        }
    }
}
